components:
    schemas:
        Product:
            description:
                A product with a name, price, and stock quantity.
            properties:
                productId:
                    description:
                        The product's ID
                    type: integer
                name:
                    description:
                        The product's name
                    type: string
                price:
                    description:
                        The product's price, in dollars
                    type: integer
            type: object
info:
    description:
        ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Product Catalog API"
    version: v1.0
openapi: 3.0.1
paths:
    "/entities/{productId}":
        get:
            operationId: getProduct
            parameters:
                - in: path
                  name: productId
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Product"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Product"
                    description:
                        ""
            tags: ["Product"]