apiDir: "../r3b2-api/src/main/java"
apiPackagePath: "com.acme.r3b2.product.catalog"
application:
    baseURI: "/product-catalog"
    className: "ProductCatalogApplication"
    name: "R3B2.Acme.Product.Catalog"
author: "Liferay"