components:
    schemas:
        Foo:
            description:
                A dummy object that has no meaning.
            properties:
                description:
                    description:
                        Say something about your Foo.
                    type: string
                id:
                    description:
                        The Foo's ID
                    format: int64
                    type: integer
                name:
                    description:
                        The title of your Foo.
                    type: string
            type: object
        Goo:
            description:
                Another dummy object to go with Foo.
            properties:
                description:
                    description:
                        Say something about your Goo.
                    type: string
                fooId:
                    description:
                        The associated Foo's ID.
                    format: int64
                    type: integer
                id:
                    description:
                        The Goo's ID
                    format: int64
                    type: integer
                name:
                    description:
                        The title of your Goo.
                    type: string
info:
    description:
        "API to return a Foo."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Foo API"
    version: v1.0
openapi: 3.0.1
paths:
    "/foo":
        get:
            description:
                ""
            operationId: getFooPage
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Foo"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Foo"
                                type: array
                    description:
                        "Returns the Foo matching the given product ID."
            tags: [ "Foo" ]
        post:
            description:
                ""
            operationId: postFoo
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        ""
            tags: ["Foo"]
    "/foo/{fooId}":
        delete:
            description:
                ""
            operationId: deleteFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
                    description:
                        ""
            tags: [ "Foo" ]
        get:
            description:
                ""
            operationId: getFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        "Returns the Foo matching the given product ID."
            tags: ["Foo"]
        patch:
            description:
                ""
            operationId: patchFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        ""
            tags: [ "Foo" ]
        put:
            description:
                ""
            operationId: putFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
                    description:
                        ""
            tags: [ "Foo" ]
    "/foo/{fooId}/goos":
        get:
            description:
                ""
            operationId: getFooGoosPage
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Goo"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Goo"
                                type: array
                    description:
                        "Gets all Goos related to a Foo."
            tags: ["Goo"]
        post:
            description:
                ""
            operationId: postFooGoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Goo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Goo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
                    description:
                        ""
            tags: [ "Goo" ]
    "/goo/{gooId}":
        delete:
            description:
                ""
            operationId: deleteGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
                    description:
                        ""
            tags: [ "Goo" ]
        get:
            description:
                ""
            operationId: getGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
                    description:
                        "Returns the Goo matching the given product ID."
            tags: [ "Goo" ]
        patch:
            description:
                ""
            operationId: patchGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Goo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Goo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
                    description:
                        ""
            tags: [ "Goo" ]
        put:
            description:
                ""
            operationId: putGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Goo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Goo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
                    description:
                        ""
            tags: [ "Goo" ]